project:
  type: book
  output-dir: docs

book:
  title: "CASA0023_Workbook"
  author: "Aaron Eunson"
  date: "23/01/2024"
  chapters:
    - index.qmd
    - Week1.qmd
    - Week2.qmd
    - Week3.qmd
    - Week4.qmd
    - Week6.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

