# Introduction  {.unnumbered}

Hi! I'm Aaron :)

Originally, from Plymouth, UK - I moved to London 4 years ago to start studying Urban Planning, Design and Mangement BSc at UCL (within the Bartlett School of Planning). My interest in planning stemmed from a desire to understand the complex worlds we live in. Cities are completely built by us on this planet and I find them to be highly interesting phenomena. They almost function like that of a living organism and COVID-19 (the year it hit was my first year of uni!) really demonstrated this. Our cities were left desolate and we suddenly had to re-imagine the way in which we do everything. I find that this has become quite a foundational experience for me.

During my time studying on the BSc, I developed a significant interest in data. I have always enjoyed working with numbers having studied maths, physics and engineering in school, but data is such an interesting and beautiful lens through which to see the world - and indeed it can actually be beautiful!

To Following from this I embarked on the current MSc (Urban Spatial Science MSc), within the Centre for Advanced Spatial Analysis - it was quite a long distance between this and my undergrad university! I had to move an across a whole... faculty.

I have yet to start working - that exciting step of life awaits for me in September 2024! But I have completed work placements and internships with Quod, TfL and Savills and have volunteered with JustSpace and Migrateful. I also have a part-time job as a wine advisor - not remotely related to remote sensing, but am hoping to fuse the love of wine and love of data for my dissertation by mapping the future UK wine industry. I am quite excited to get stuck into this project and am sure this module (Remotely Sensing Cities and Environments) will no doubt be of use for this undertaking!!
