# References {.unnumbered}

Adeli, S., Salehi, B., Mahdianpari, M., Quackenbush, L.J., Brisco, B., Tamiminia, H. and Shaw, S. (2020). Wetland Monitoring Using SAR Data: A Meta-Analysis and Comprehensive Review. Remote Sensing, 12(14), p.2190. doi:https://doi.org/10.3390/rs12142190.

Brecht (2018). Remote Sensing Indices. \[online\] Regen Network Development. Available at: https://medium.com/regen-network/remote-sensing-indices-389153e3d947 \[Accessed 22 Mar. 2024\].

Carr, C. and Hesse, M. (2020). When Alphabet Inc. Plans Toronto's Waterfront: New Post-Political Modes of Urban Governance. Urban Planning, 5(1), p.69. doi:https://doi.org/10.17645/up.v5i1.2519.

Colven, E. (2021). Better flood management can save Jakarta. \[online\] East Asia Forum. Available at: https://eastasiaforum.org/2021/07/13/better-flood-management-can-save-jakarta/ \[Accessed 22 Mar. 2024\].

Conservation Technology Information Center (n.d.). OpTIS_Information :: Conservation Technology Information Center. \[online\] www.ctic.org. Available at: https://www.ctic.org/OpTIS_Information \[Accessed 22 Mar. 2024\].

Decidim (n.d.). Free Open-Source participatory democracy for cities and organizations \| Decidim. \[online\] decidim.org. Available at: https://decidim.org/ \[Accessed 22 Mar. 2024\].

Earth Science Data Systems, N. (2023). What Is Remote Sensing? \[online\] Earthdata. Available at: https://www.earthdata.nasa.gov/learn/backgrounders/remote-sensing.

Esri Indonesia (2020). ESSC's GIS-powered Jakarta Flood Map Portal. \[online\] Esri Indonesia. Available at: https://esriindonesia.co.id/news/esscs-gis-powered-jakarta-flood-map-portal \[Accessed 22 Mar. 2024\].

Garschagen, M., Surtiari, G. and Harb, M. (2018). Is Jakarta's New Flood Risk Reduction Strategy Transformational? Sustainability, 10(8), p.2934. doi:https://doi.org/10.3390/su10082934.

GOV.UK (2023). PM recommits UK to Net Zero by 2050 and pledges a 'fairer' path to achieving target to ease the financial burden on British families. \[online\] GOV.UK. Available at: https://www.gov.uk/government/news/pm-recommits-uk-to-net-zero-by-2050-and-pledges-a-fairer-path-to-achieving-target-to-ease-the-financial-burden-on-british-families.

Hansen, M.C., Potapov, P.V., Moore, R., Hancher, M., Turubanova, S.A., Tyukavina, A., Thau, D., Stehman, S.V., Goetz, S.J., Loveland, T.R., Kommareddy, A., Egorov, A., Chini, L., Justice, C.O. and Townshend, J.R.G. (2013). High-Resolution Global Maps of 21st-Century Forest Cover Change. Science, \[online\] 342(6160), pp.850--853. doi:https://doi.org/10.1126/science.1244693.

Hill, E. (2013). Indonesia's Ambitious Plans to Reduce Jakarta Flooding -- FloodList. \[online\] floodlist.com. Available at: https://floodlist.com/asia/plans-reduce-jakarta-flooding \[Accessed 22 Mar. 2024\].

https://projects.rvo.nl/programmes/nl-kvk-27378529-23583 (2020). Jakarta Coastal Defence Strategy (JCDS) \| Project Database CMS. \[online\] projects.rvo.nl. Available at: https://projects.rvo.nl/programmes/nl-kvk-27378529-23583 \[Accessed 22 Mar. 2024\].

Hu, Y., Zhang, Q., Zhang, Y. and Yan, H. (2018). A Deep Convolution Neural Network Method for Land Cover Mapping: A Case Study of Qinhuangdao, China. Remote Sensing, 10(12), p.2053. doi:https://doi.org/10.3390/rs10122053.

Khomami, N., Arts, N.K. and correspondent, culture (2023). Britons go map-crazy, with geographical games and books becoming bestsellers. The Guardian. \[online\] 31 Oct. Available at: https://www.theguardian.com/travel/2023/oct/31/metro-memory-and-tim-marshall-put-cartography-back-on-the-map \[Accessed 22 Mar. 2024\].

Kobayashi, S. and Ide, H. (2022). Rice Crop Monitoring Using Sentinel-1 SAR Data: A Case Study in Saku, Japan. Remote Sensing, 14(14), p.3254. doi:https://doi.org/10.3390/rs14143254.

Louisiana Museum of Modern Art (n.d.). Seeing like a machine - with artist Trevor Paglen. \[online\] Louisiana Museum of Modern Art. Available at: https://louisiana.dk/en/event/seeing-like-a-machine-moed-kunstner-trevor-paglen/ \[Accessed 22 Mar. 2024\].

Moore, R. (2022). Introducing Earth Engine for governments and businesses. \[online\] Google. Available at: https://blog.google/products/earth/introducing-earth-engine-for-governments-and-businesses/ \[Accessed 22 Mar. 2024\].

Netherlands Enterprise Agency (2020). Master Plan National Capital Integrated Coastal Development \| Project Database CMS. \[online\] projects.rvo.nl. Available at: https://projects.rvo.nl/projects/nl-kvk-27378529-pvwb12003 \[Accessed 22 Mar. 2024\].

Prime, G.W. (2022). Virtual Singapore -- Building a 3D-Empowered Smart Nation. \[online\] Geospatial World. Available at: https://www.geospatialworld.net/prime/case-study/national-mapping/virtual-singapore-building-a-3d-empowered-smart-nation/ \[Accessed 22 Mar. 2024\].

Regrow (n.d.). Case studies in regenerative agriculture. \[online\] www.regrow.ag. Available at: https://www.regrow.ag/case-studies \[Accessed 22 Mar. 2024\].

tirumalachandr (2022). CART (Classification And Regression Tree) in Machine Learning. \[online\] GeeksforGeeks. Available at: https://www.geeksforgeeks.org/cart-classification-and-regression-tree-in-machine-learning/ \[Accessed 22 Mar. 2024\].

United Nations (2015). The 17 Sustainable Development Goals. \[online\] United Nations. Available at: https://sdgs.un.org/goals \[Accessed 22 Mar. 2024\].

USGS - U.S. Geological Survey (2023). EarthExplorer. \[online\] Usgs.gov. Available at: https://earthexplorer.usgs.gov/ \[Accessed 22 Mar. 2024\].

Woodhouse, I. (2022). Google Earth Engine for commercial use \| Blog \| Earth Blox. \[online\] www.earthblox.io. Available at: https://www.earthblox.io/blog/google-earth-engine-for-commercial-use-what-the-new-access-means-for-your-impact-business \[Accessed 22 Mar. 2024\].

World Resources Institute (2021). Global Forest Watch. \[online\] Globalforestwatch.org. Available at: https://www.globalforestwatch.org/ \[Accessed 22 Mar. 2024\].

Zhao, Q., Yu, L., Li, X., Peng, D., Zhang, Y. and Gong, P. (2021). Progress and Trends in the Application of Google Earth and Google Earth Engine. Remote Sensing, 13(18), p.3778. doi:https://doi.org/10.3390/rs13183778.
